language: python
services:
  - docker
env:
  global:
    - KILI_API_ENDPOINT=https://staging.cloud.kili-technology.com/api/label/graphql
    - secure: "Fp+CxLa/DhQl59yQHsEC366aFbf2lhxnBiG0IQJPangsEh2LDyrcX3bVONR20kB4eM4aBh5gtN6QihhdZzoE11tEiIWkhl+bc6hbs1/GenlXOS1Px8Qycbp+1s58AkPOqiIcpiDkH8y7DCtEQDqQY4OlobSspEgJunSwZ1k0c+YFqS9+Ydfs37OsEs17xvjwc04gK3EklxdbgSchfijKN5XLclOPPIhjO3uezKcw5vVfWxCjFSN/8U8RB6tTjHWJnH29WLq+FMGbqemDfnJCd0Gxo8CdAzTBMu6UWUMViSTmBV4e2tiWkoabhbc3kskY4vZiMfoM9/GrCIzPNT/KFi+yTZcVzoRNf6g5ArgxWHox4g+dqBNXBQ3b8zVU4urdvrtyid7I/YA1v95iWAWDCsSmXCBRfldBieR67g+qOT8I8ZDSSo1V03SBHyVXNgyR0I7AQihkVa8d9ZdwQEF3Q/DjHYnAZLKBIcfGrllAMHjw9mn8bZvjDLv9bRWZiXQ2+jJPm0vsBhQjriwrLAEZ5t2Fn21m13H1+M1/ol2pguX/bHd6ubmGx5l9XrIZQh3bmRycSKfOtTI+OaaLhdxFGsln++ctq7QgK0OkKv0LAakkOCLrSaz0CAytZGlZFBSFqY2b/7wlQf2k/d0Jbz4nK6fyp+F05oWyWHSjkOq7tYk="
    - secure: "dyNZhCmIsMNdnB8+7awU4gPF9HVpcXKaELR7GxaSizxcIwRAmkhiIv+ZQvuC4i1aM9oclKvwDOXJVKap45VRAy77afTwcI7IxRCPfdWM6Vnf4NQSZs83FXu7461SjKKRC02qPSOpCVeAtcye38bKul9WhJCvQTCQjHJUMONP69v1R3R8vFm+PrR/aM8l6mSG7P16d87WkhOqqloE6C3oHWwBxeIHMECBlJV3oX84mi3YCC+Q9piESqUXq3ndDgYb1bRsOXWwHitpIJp20AHZrUkAVGpEhMpx2qJxVn5cJMI7Ex8X04s6Udq95vGRVrY6pH5znAW921ore8FAcRq+nWXjQPQZC364ejkKG7UG6yNc5k8BgdSLEZdSKwHff1uNp7wEH2R4lQfgn6sKptLXT/rgKX1MfPnt1Q1RxnOkYCXO0oaYMlxcTvkYUuprmdtXyEhKcLr+agCsY7cZbpmES1uvSUxwvo0JzfQMH5NsVD4W67mdERj/Nt83aFNoRnKJPyAzFyzzOxa4KWARJg+cM/DGQn+p649eyn/BjTQ8bc2Y7ynoRgCZfZUPZzvh/8aZWCcLvGpBLmvCZ1qBB8FshJuWb88v2asw75BMCQIWV9Ln/lqYjeuE8ec5yGHHdcMA5/NoAQv8DXIW3XxoGxgCwERRvUlIy82pn732UjHoARc="
jobs:
  include:
    - &test-recipes
      stage: Test *.ipynb in recipes
      script:
        - docker pull ${DOCKER_IMAGE}
        - |
          docker run \
            --env KILI_API_ENDPOINT=${KILI_API_ENDPOINT} \
            --env KILI_USER_EMAIL=${KILI_USER_EMAIL} \
            --env KILI_USER_PASSWORD=${KILI_USER_PASSWORD} \
            ${DOCKER_IMAGE} /bin/sh -c "cd /root && \
              apt-get install -y gcc && \
              git clone --branch ${TRAVIS_BRANCH} https://github.com/kili-technology/kili-playground.git && \
              pip install ./kili-playground && \
              jupyter nbconvert \
                --to notebook \
                --ExecutePreprocessor.kernel_name=python3 \
                --ExecutePreprocessor.timeout=500 \
                --execute /root/kili-playground/${NOTEBOOK_PATH}"
      env:
        - DOCKER_IMAGE=continuumio/anaconda3:2020.02
        - NOTEBOOK_PATH=recipes/image-object-detection-with-yolo/main.ipynb
    # Declare other tests as follow:
    # - <<: *test-recipes
    #   env:
    #     - DOCKER_IMAGE=docker/image
    #     - NOTEBOOK_PATH=recipes/path/to.ipynb
